name: Build PDF documentation

on:
  push:
    paths:
      - 'src/**/*.md'
      - '*.tex'
      - 'build_docs.py'
      - 'Dockerfile'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'src/**/*.md'
      - '*.tex'
      - 'build_docs.py'
      - 'Dockerfile'
      - '.github/workflows/**'

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build docs Docker image
        run: docker build -t docs-builder .

      - name: Run build_docs.py inside container
        run: |
          docker run \
            --rm \
            -v "${{ github.workspace }}:/docs" \
            docs-builder \
            python3 build_docs.py build

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation-pdf
          path: build/main.pdf